export interface ApiError {
  code: string;
  message: string;
}

export const ERROR_CODES = {
  SESSION_NOT_FOUND: "SESSION_NOT_FOUND",
  INVALID_SCENARIO: "INVALID_SCENARIO",
  AI_CALL_FAILED: "AI_CALL_FAILED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  WS_CONNECTION_FAILED: "WS_CONNECTION_FAILED",
} as const;
